# -*- coding: utf-8 -*-
"""korelasi_fitur.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14piFeA16Qay32OV99lb9gJjclB1X-8Up
"""

import pandas as pd
import seaborn as sns

data = pd.read_csv("/content/Iris.csv")

data.head()

sns.scatterplot(x='SepalLengthCm', y='PetalWidthCm', data=data);

from scipy.stats import pearsonr

corr, _ = pearsonr(data['SepalLengthCm'], data['PetalWidthCm'])
print('Korelasi menggunakan Pearsons: %.3f' % corr)

from scipy.stats import spearmanr 

corr1 = spearmanr(data['SepalLengthCm'], data['PetalWidthCm'])[0]
print('Korelasi menggunakan Rank Spearman: %.3f' % corr1)

from scipy.stats import kendalltau

corr2, _ = kendalltau(data['SepalLengthCm'], data['PetalWidthCm'])
print('Korelasi menggunakan Kendall Tau: %.3f' % corr2)

